# Generated by Django 4.2.5 on 2023-09-22 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explink',
            name='created_at',
        ),
        migrations.AddField(
            model_name='explink',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
