# Generated by Django 4.2.5 on 2023-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_explink_created_at_explink_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
