# Generated by Django 4.2.5 on 2023-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_tier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_s_height',
            field=models.IntegerField(default=200),
        ),
    ]
