# Generated by Django 4.2.5 on 2023-09-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_tier_thumbnail_s_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_m_height',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_s_height',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
