# Generated by Django 4.2.5 on 2023-09-24 10:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_tier_thumbnail_m_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explink',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=300)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=30000))]),
        ),
        migrations.AlterField(
            model_name='tier',
            name='thumbnail_s_height',
            field=models.PositiveIntegerField(default=200, validators=[django.core.validators.MaxValueValidator(1920)]),
        ),
    ]
