# Generated by Django 4.2.5 on 2023-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_tier_exp_link_alter_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
